### PR TITLE
Laotian666

### PR DESCRIPTION
**Pull request by tianhongce**
asdasdfasdfasfdasdfasdf

---
This change is [Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)

### CODE REVIEW

**Review by Diorzz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Diorzz and @tianhongce)

___
*[file, line 14 at r2](https://reviewable.io/reviews/diorzz/algorithm/6#-LiDheeL4pCI_732bAMn:-LiDheeL4pCI_732bAMo:bliikf3) ([raw file](https://github.com/diorzz/algorithm/blob/6e85634afecf52086ff86d3d5192844f90fdf35e/file#L14)):*
> ```
> sdg
> sdgsm,fsdfsd
> f
> ```

你写的啥

**Review by Diorzz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Diorzz and @tianhongce)

___
*[file, line 23 at r2](https://reviewable.io/reviews/diorzz/algorithm/6#-LiDhyxM4fIpd_ZXY7gl:-LiDhyxM4fIpd_ZXY7gm:b-3pu91b) ([raw file](https://github.com/diorzz/algorithm/blob/6e85634afecf52086ff86d3d5192844f90fdf35e/file#L23)):*
> ```
> sdf
> sdf
>  sd
> ```

这块改一下

**Review by Diorzz — COMMENTED** [review]
？？

> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6#-:-LiDiaU61IkZXJMr0A2d:b4bmp1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tianhongce)

**Review by tianhongce — COMMENTED** [review]
ok

> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6#-:-LiDjSqi4E4NpnAOJE6j:b32wtd)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Diorzz and @tianhongce)

___
*[file, line 14 at r2](https://reviewable.io/reviews/diorzz/algorithm/6#-LiDheeL4pCI_732bAMn:-LiDjV3oCsbl6JWyzpGz:bnixvqj) ([raw file](https://github.com/diorzz/algorithm/blob/6e85634afecf52086ff86d3d5192844f90fdf35e/file#L14)):*
<details><summary><i>Previously, Diorzz (zhaozheng) wrote…</i></summary><blockquote>

你写的啥
</blockquote></details>

我sb了
___
*[file, line 23 at r2](https://reviewable.io/reviews/diorzz/algorithm/6#-LiDhyxM4fIpd_ZXY7gl:-LiDjWbq4v0xvdUr9cKA:bqo3xx) ([raw file](https://github.com/diorzz/algorithm/blob/6e85634afecf52086ff86d3d5192844f90fdf35e/file#L23)):*
<details><summary><i>Previously, Diorzz (zhaozheng) wrote…</i></summary><blockquote>

这块改一下
</blockquote></details>

好的征哥哥

**Review by Diorzz — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Diorzz — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Diorzz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6)* status: all files reviewed, 1 unresolved discussion (waiting on @Diorzz)

*[a discussion](https://reviewable.io/reviews/diorzz/algorithm/6#-LiDliKnERH-UN_hM7f_:-LiDliKnERH-UN_hM7fa:b4wlnya) (no related file):*
Working...

---

**Review by Diorzz — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/diorzz/algorithm/6#-:-LiGxwy_AKApoeB6Gg_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
